create table if not exists public.historic_match_scorers (
  id bigint generated by default as identity primary key,
  season text not null,
  fixture_date date not null,
  competition_name text not null,
  home_team_name text not null,
  away_team_name text not null,
  home_goals integer,
  away_goals integer,
  player_name text not null,
  team_name text not null,
  goals integer not null check (goals > 0),
  source_url text not null,
  created_at timestamptz not null default now(),
  unique (source_url, player_name, team_name)
);

create index if not exists historic_match_scorers_player_season_idx
  on public.historic_match_scorers (lower(player_name), season);

alter table public.historic_match_scorers enable row level security;

grant select on public.historic_match_scorers to anon, authenticated;

drop policy if exists "Historic match scorers are publicly readable"
  on public.historic_match_scorers;

create policy "Historic match scorers are publicly readable"
  on public.historic_match_scorers
  for select
  to anon, authenticated
  using (true);
